# Generated by Django 3.1.2 on 2020-10-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innsaver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='surname',
            field=models.CharField(max_length=36),
        ),
    ]
