# Generated by Django 3.1.2 on 2020-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innsaver', '0004_auto_20201012_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='adress',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='human',
            name='inn',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='human',
            name='phoneNumber',
            field=models.CharField(default='', max_length=12),
        ),
    ]
